### ISSUE TITLE
Enhancement: support pulling in all data

### ISSUE THREAD

**Issue by ryjones** [cyberscribbleorg/EventFlow#11]
I would like a config.json option that would just read all of the data and insert it, instead of data for a specific person.

**Comment by cyberscribbleorg** [comment]
Would you be able to clarify a little  ?
- All the data for a specific project ? 
- just entire dump of github archive in to psql ?

**Comment by ryjones** [comment]
just dump the whole thing in

**Comment by cyberscribbleorg** [comment]
It is an interesting ask ;-) 

- Suggestion of user/project being blank is  good but since our automated dashboards are derived from these fields it might not be feasible
- Included a mode field in the config.json file with values '@' and '*' where @ is specific targeted harvesting and * is a pure github archive dump 
- Current task architecture would not be optimum for wildcard dump, which we might have to revisit after our current priorities , in fact for wildcard dump the benchmark shows for an hour worth of data dumping it takes 5min on my weak virtualbox VM

All can be found @ https://github.com/cyberscribbleorg/EventFlow/pull/12
